name: CI/CD

# Триггеры: пуш в main и пуш тегов вида v*
on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

# Настройки среды
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install YC CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Auth YC
        run: |
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > key.json
          yc config set service-account-key key.json

      - name: Docker auth
        run: yc container registry configure-docker

      - name: Build image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/devops-nginx:latest ./app

      - name: Push image
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/devops-nginx:latest

  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install YC CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Auth YC
        run: |
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > key.json
          yc config set service-account-key key.json

      - name: Get kubeconfig
        run: yc managed-kubernetes cluster get-credentials k8s-cluster --external

      - name: Deploy to K8s
        run: kubectl apply -f k8s/